import {
    LayoutDashboard,
    BookOpen,
    Building2,
    Book,
    MessageSquare,
    Image as ImageIcon,
    ScrollText,
    Users,
    MessageCircle,
    Calendar,
    BarChart3,
    Settings,
    UserCog,
    ShieldCheck,
    FileText,
    Database,
    Activity,
    HardDriveDownload,
    Wrench,
    Globe,
    CreditCard,
    FolderKanban,
    Film,
} from 'lucide-react';
import type { NavItem } from './dashboard-layout';

export const userNav: NavItem[] = [
    { title: 'Dashboard', url: '/user', icon: LayoutDashboard },
    { title: 'Learning Modules', url: '/user/learning-modules', icon: BookOpen },
    { title: 'Cultural Repository', url: '/user/cultural-repository', icon: Building2 },
    { title: 'Vocabulary Dictionary', url: '/user/vocabulary-dictionary', icon: Book },
    { title: 'AI Chatbot', url: '/user/ai-chatbot', icon: MessageSquare },
    { title: 'Multimedia Gallery', url: '/user/multimedia-gallery', icon: ImageIcon },
    { title: 'Storytelling Archive', url: '/user/storytelling-archive', icon: ScrollText },
    { title: 'Community Contributions', url: '/user/community-contributions', icon: Users },
    { title: 'Feedback', url: '/user/feedback', icon: MessageCircle },
    { title: 'My Progress', url: '/user/progress', icon: BarChart3 },
    { title: 'Settings', url: '/user/settings', icon: Settings },
];

export const adminNav: NavItem[] = [
    { title: 'Dashboard', url: '/admin', icon: LayoutDashboard },
    { title: 'Learning Materials', url: '/admin/learning-materials', icon: BookOpen },
    { title: 'Cultural Repository', url: '/admin/cultural-repository', icon: Building2 },
    { title: 'Multimedia Management', url: '/admin/multimedia', icon: Film },
    { title: 'Community Contributions', url: '/admin/contributions', icon: Users },
    { title: 'Feedback Management', url: '/admin/feedback', icon: MessageCircle },
    { title: 'User Management', url: '/admin/users', icon: UserCog },
    { title: 'Events Management', url: '/admin/events', icon: Calendar },
    { title: 'Reports & Analytics', url: '/admin/reports', icon: BarChart3 },
    { title: 'System Settings', url: '/admin/settings', icon: Settings },
];

export const superNav: NavItem[] = [
    { title: 'Dashboard', url: '/super', icon: LayoutDashboard },
    { title: 'System Overview', url: '/super/overview', icon: Activity },
    { title: 'User Management', url: '/super/users', icon: UserCog },
    { title: 'Role & Permission Management', url: '/super/roles', icon: ShieldCheck },
    { title: 'Content Management', url: '/super/content', icon: FolderKanban },
    { title: 'Database Management', url: '/super/database', icon: Database },
    { title: 'System Settings', url: '/super/settings', icon: Settings },
    { title: 'Activity Logs', url: '/super/logs', icon: FileText },
    { title: 'Backup & Restore', url: '/super/backup', icon: HardDriveDownload },
    { title: 'Reports & Analytics', url: '/super/reports', icon: BarChart3 },
    { title: 'Security Management', url: '/super/security', icon: ShieldCheck },
    { title: 'Site Configuration', url: '/super/site', icon: Globe },
    { title: 'Maintenance', url: '/super/maintenance', icon: Wrench },
    { title: 'Subscription Management', url: '/super/subscription', icon: CreditCard },
];
