/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as SuperRouteImport } from './routes/super'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user.index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UserVocabularyDictionaryRouteImport } from './routes/user.vocabulary-dictionary'
import { Route as UserStorytellingArchiveRouteImport } from './routes/user.storytelling-archive'
import { Route as UserSettingsRouteImport } from './routes/user.settings'
import { Route as UserProgressRouteImport } from './routes/user.progress'
import { Route as UserMultimediaGalleryRouteImport } from './routes/user.multimedia-gallery'
import { Route as UserLearningModulesRouteImport } from './routes/user.learning-modules'
import { Route as UserFeedbackRouteImport } from './routes/user.feedback'
import { Route as UserEventsRouteImport } from './routes/user.events'
import { Route as UserCulturalRepositoryRouteImport } from './routes/user.cultural-repository'
import { Route as UserCommunityContributionsRouteImport } from './routes/user.community-contributions'
import { Route as UserAiChatbotRouteImport } from './routes/user.ai-chatbot'
import { Route as SuperUsersRouteImport } from './routes/super.users'
import { Route as SuperSubscriptionRouteImport } from './routes/super.subscription'
import { Route as SuperSiteRouteImport } from './routes/super.site'
import { Route as SuperSettingsRouteImport } from './routes/super.settings'
import { Route as SuperSecurityRouteImport } from './routes/super.security'
import { Route as SuperRolesRouteImport } from './routes/super.roles'
import { Route as SuperReportsRouteImport } from './routes/super.reports'
import { Route as SuperOverviewRouteImport } from './routes/super.overview'
import { Route as SuperMaintenanceRouteImport } from './routes/super.maintenance'
import { Route as SuperLogsRouteImport } from './routes/super.logs'
import { Route as SuperDatabaseRouteImport } from './routes/super.database'
import { Route as SuperContentRouteImport } from './routes/super.content'
import { Route as SuperBackupRouteImport } from './routes/super.backup'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminMultimediaRouteImport } from './routes/admin.multimedia'
import { Route as AdminLearningMaterialsRouteImport } from './routes/admin.learning-materials'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminCulturalRepositoryRouteImport } from './routes/admin.cultural-repository'
import { Route as AdminContributionsRouteImport } from './routes/admin.contributions'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserVocabularyDictionaryRoute =
  UserVocabularyDictionaryRouteImport.update({
    id: '/vocabulary-dictionary',
    path: '/vocabulary-dictionary',
    getParentRoute: () => UserRoute,
  } as any)
const UserStorytellingArchiveRoute = UserStorytellingArchiveRouteImport.update({
  id: '/storytelling-archive',
  path: '/storytelling-archive',
  getParentRoute: () => UserRoute,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserRoute,
} as any)
const UserProgressRoute = UserProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => UserRoute,
} as any)
const UserMultimediaGalleryRoute = UserMultimediaGalleryRouteImport.update({
  id: '/multimedia-gallery',
  path: '/multimedia-gallery',
  getParentRoute: () => UserRoute,
} as any)
const UserLearningModulesRoute = UserLearningModulesRouteImport.update({
  id: '/learning-modules',
  path: '/learning-modules',
  getParentRoute: () => UserRoute,
} as any)
const UserFeedbackRoute = UserFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => UserRoute,
} as any)
const UserEventsRoute = UserEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => UserRoute,
} as any)
const UserCulturalRepositoryRoute = UserCulturalRepositoryRouteImport.update({
  id: '/cultural-repository',
  path: '/cultural-repository',
  getParentRoute: () => UserRoute,
} as any)
const UserCommunityContributionsRoute =
  UserCommunityContributionsRouteImport.update({
    id: '/community-contributions',
    path: '/community-contributions',
    getParentRoute: () => UserRoute,
  } as any)
const UserAiChatbotRoute = UserAiChatbotRouteImport.update({
  id: '/ai-chatbot',
  path: '/ai-chatbot',
  getParentRoute: () => UserRoute,
} as any)
const SuperUsersRoute = SuperUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSubscriptionRoute = SuperSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSiteRoute = SuperSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSettingsRoute = SuperSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSecurityRoute = SuperSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SuperRoute,
} as any)
const SuperRolesRoute = SuperRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SuperRoute,
} as any)
const SuperReportsRoute = SuperReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SuperRoute,
} as any)
const SuperOverviewRoute = SuperOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => SuperRoute,
} as any)
const SuperMaintenanceRoute = SuperMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => SuperRoute,
} as any)
const SuperLogsRoute = SuperLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SuperRoute,
} as any)
const SuperDatabaseRoute = SuperDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => SuperRoute,
} as any)
const SuperContentRoute = SuperContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => SuperRoute,
} as any)
const SuperBackupRoute = SuperBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => SuperRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMultimediaRoute = AdminMultimediaRouteImport.update({
  id: '/multimedia',
  path: '/multimedia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearningMaterialsRoute = AdminLearningMaterialsRouteImport.update({
  id: '/learning-materials',
  path: '/learning-materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCulturalRepositoryRoute = AdminCulturalRepositoryRouteImport.update({
  id: '/cultural-repository',
  path: '/cultural-repository',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContributionsRoute = AdminContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/super': typeof SuperRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/contributions': typeof AdminContributionsRoute
  '/admin/cultural-repository': typeof AdminCulturalRepositoryRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/learning-materials': typeof AdminLearningMaterialsRoute
  '/admin/multimedia': typeof AdminMultimediaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/super/backup': typeof SuperBackupRoute
  '/super/content': typeof SuperContentRoute
  '/super/database': typeof SuperDatabaseRoute
  '/super/logs': typeof SuperLogsRoute
  '/super/maintenance': typeof SuperMaintenanceRoute
  '/super/overview': typeof SuperOverviewRoute
  '/super/reports': typeof SuperReportsRoute
  '/super/roles': typeof SuperRolesRoute
  '/super/security': typeof SuperSecurityRoute
  '/super/settings': typeof SuperSettingsRoute
  '/super/site': typeof SuperSiteRoute
  '/super/subscription': typeof SuperSubscriptionRoute
  '/super/users': typeof SuperUsersRoute
  '/user/ai-chatbot': typeof UserAiChatbotRoute
  '/user/community-contributions': typeof UserCommunityContributionsRoute
  '/user/cultural-repository': typeof UserCulturalRepositoryRoute
  '/user/events': typeof UserEventsRoute
  '/user/feedback': typeof UserFeedbackRoute
  '/user/learning-modules': typeof UserLearningModulesRoute
  '/user/multimedia-gallery': typeof UserMultimediaGalleryRoute
  '/user/progress': typeof UserProgressRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/storytelling-archive': typeof UserStorytellingArchiveRoute
  '/user/vocabulary-dictionary': typeof UserVocabularyDictionaryRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/contributions': typeof AdminContributionsRoute
  '/admin/cultural-repository': typeof AdminCulturalRepositoryRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/learning-materials': typeof AdminLearningMaterialsRoute
  '/admin/multimedia': typeof AdminMultimediaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/super/backup': typeof SuperBackupRoute
  '/super/content': typeof SuperContentRoute
  '/super/database': typeof SuperDatabaseRoute
  '/super/logs': typeof SuperLogsRoute
  '/super/maintenance': typeof SuperMaintenanceRoute
  '/super/overview': typeof SuperOverviewRoute
  '/super/reports': typeof SuperReportsRoute
  '/super/roles': typeof SuperRolesRoute
  '/super/security': typeof SuperSecurityRoute
  '/super/settings': typeof SuperSettingsRoute
  '/super/site': typeof SuperSiteRoute
  '/super/subscription': typeof SuperSubscriptionRoute
  '/super/users': typeof SuperUsersRoute
  '/user/ai-chatbot': typeof UserAiChatbotRoute
  '/user/community-contributions': typeof UserCommunityContributionsRoute
  '/user/cultural-repository': typeof UserCulturalRepositoryRoute
  '/user/events': typeof UserEventsRoute
  '/user/feedback': typeof UserFeedbackRoute
  '/user/learning-modules': typeof UserLearningModulesRoute
  '/user/multimedia-gallery': typeof UserMultimediaGalleryRoute
  '/user/progress': typeof UserProgressRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/storytelling-archive': typeof UserStorytellingArchiveRoute
  '/user/vocabulary-dictionary': typeof UserVocabularyDictionaryRoute
  '/admin': typeof AdminIndexRoute
  '/super': typeof SuperIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/super': typeof SuperRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/contributions': typeof AdminContributionsRoute
  '/admin/cultural-repository': typeof AdminCulturalRepositoryRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/learning-materials': typeof AdminLearningMaterialsRoute
  '/admin/multimedia': typeof AdminMultimediaRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/super/backup': typeof SuperBackupRoute
  '/super/content': typeof SuperContentRoute
  '/super/database': typeof SuperDatabaseRoute
  '/super/logs': typeof SuperLogsRoute
  '/super/maintenance': typeof SuperMaintenanceRoute
  '/super/overview': typeof SuperOverviewRoute
  '/super/reports': typeof SuperReportsRoute
  '/super/roles': typeof SuperRolesRoute
  '/super/security': typeof SuperSecurityRoute
  '/super/settings': typeof SuperSettingsRoute
  '/super/site': typeof SuperSiteRoute
  '/super/subscription': typeof SuperSubscriptionRoute
  '/super/users': typeof SuperUsersRoute
  '/user/ai-chatbot': typeof UserAiChatbotRoute
  '/user/community-contributions': typeof UserCommunityContributionsRoute
  '/user/cultural-repository': typeof UserCulturalRepositoryRoute
  '/user/events': typeof UserEventsRoute
  '/user/feedback': typeof UserFeedbackRoute
  '/user/learning-modules': typeof UserLearningModulesRoute
  '/user/multimedia-gallery': typeof UserMultimediaGalleryRoute
  '/user/progress': typeof UserProgressRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/storytelling-archive': typeof UserStorytellingArchiveRoute
  '/user/vocabulary-dictionary': typeof UserVocabularyDictionaryRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/super'
    | '/user'
    | '/admin/contributions'
    | '/admin/cultural-repository'
    | '/admin/events'
    | '/admin/feedback'
    | '/admin/learning-materials'
    | '/admin/multimedia'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/super/backup'
    | '/super/content'
    | '/super/database'
    | '/super/logs'
    | '/super/maintenance'
    | '/super/overview'
    | '/super/reports'
    | '/super/roles'
    | '/super/security'
    | '/super/settings'
    | '/super/site'
    | '/super/subscription'
    | '/super/users'
    | '/user/ai-chatbot'
    | '/user/community-contributions'
    | '/user/cultural-repository'
    | '/user/events'
    | '/user/feedback'
    | '/user/learning-modules'
    | '/user/multimedia-gallery'
    | '/user/progress'
    | '/user/settings'
    | '/user/storytelling-archive'
    | '/user/vocabulary-dictionary'
    | '/admin/'
    | '/super/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/contributions'
    | '/admin/cultural-repository'
    | '/admin/events'
    | '/admin/feedback'
    | '/admin/learning-materials'
    | '/admin/multimedia'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/super/backup'
    | '/super/content'
    | '/super/database'
    | '/super/logs'
    | '/super/maintenance'
    | '/super/overview'
    | '/super/reports'
    | '/super/roles'
    | '/super/security'
    | '/super/settings'
    | '/super/site'
    | '/super/subscription'
    | '/super/users'
    | '/user/ai-chatbot'
    | '/user/community-contributions'
    | '/user/cultural-repository'
    | '/user/events'
    | '/user/feedback'
    | '/user/learning-modules'
    | '/user/multimedia-gallery'
    | '/user/progress'
    | '/user/settings'
    | '/user/storytelling-archive'
    | '/user/vocabulary-dictionary'
    | '/admin'
    | '/super'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/super'
    | '/user'
    | '/admin/contributions'
    | '/admin/cultural-repository'
    | '/admin/events'
    | '/admin/feedback'
    | '/admin/learning-materials'
    | '/admin/multimedia'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/super/backup'
    | '/super/content'
    | '/super/database'
    | '/super/logs'
    | '/super/maintenance'
    | '/super/overview'
    | '/super/reports'
    | '/super/roles'
    | '/super/security'
    | '/super/settings'
    | '/super/site'
    | '/super/subscription'
    | '/super/users'
    | '/user/ai-chatbot'
    | '/user/community-contributions'
    | '/user/cultural-repository'
    | '/user/events'
    | '/user/feedback'
    | '/user/learning-modules'
    | '/user/multimedia-gallery'
    | '/user/progress'
    | '/user/settings'
    | '/user/storytelling-archive'
    | '/user/vocabulary-dictionary'
    | '/admin/'
    | '/super/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  SuperRoute: typeof SuperRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/vocabulary-dictionary': {
      id: '/user/vocabulary-dictionary'
      path: '/vocabulary-dictionary'
      fullPath: '/user/vocabulary-dictionary'
      preLoaderRoute: typeof UserVocabularyDictionaryRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/storytelling-archive': {
      id: '/user/storytelling-archive'
      path: '/storytelling-archive'
      fullPath: '/user/storytelling-archive'
      preLoaderRoute: typeof UserStorytellingArchiveRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/progress': {
      id: '/user/progress'
      path: '/progress'
      fullPath: '/user/progress'
      preLoaderRoute: typeof UserProgressRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/multimedia-gallery': {
      id: '/user/multimedia-gallery'
      path: '/multimedia-gallery'
      fullPath: '/user/multimedia-gallery'
      preLoaderRoute: typeof UserMultimediaGalleryRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/learning-modules': {
      id: '/user/learning-modules'
      path: '/learning-modules'
      fullPath: '/user/learning-modules'
      preLoaderRoute: typeof UserLearningModulesRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/feedback': {
      id: '/user/feedback'
      path: '/feedback'
      fullPath: '/user/feedback'
      preLoaderRoute: typeof UserFeedbackRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/events': {
      id: '/user/events'
      path: '/events'
      fullPath: '/user/events'
      preLoaderRoute: typeof UserEventsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/cultural-repository': {
      id: '/user/cultural-repository'
      path: '/cultural-repository'
      fullPath: '/user/cultural-repository'
      preLoaderRoute: typeof UserCulturalRepositoryRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/community-contributions': {
      id: '/user/community-contributions'
      path: '/community-contributions'
      fullPath: '/user/community-contributions'
      preLoaderRoute: typeof UserCommunityContributionsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/ai-chatbot': {
      id: '/user/ai-chatbot'
      path: '/ai-chatbot'
      fullPath: '/user/ai-chatbot'
      preLoaderRoute: typeof UserAiChatbotRouteImport
      parentRoute: typeof UserRoute
    }
    '/super/users': {
      id: '/super/users'
      path: '/users'
      fullPath: '/super/users'
      preLoaderRoute: typeof SuperUsersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/subscription': {
      id: '/super/subscription'
      path: '/subscription'
      fullPath: '/super/subscription'
      preLoaderRoute: typeof SuperSubscriptionRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/site': {
      id: '/super/site'
      path: '/site'
      fullPath: '/super/site'
      preLoaderRoute: typeof SuperSiteRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/settings': {
      id: '/super/settings'
      path: '/settings'
      fullPath: '/super/settings'
      preLoaderRoute: typeof SuperSettingsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/security': {
      id: '/super/security'
      path: '/security'
      fullPath: '/super/security'
      preLoaderRoute: typeof SuperSecurityRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/roles': {
      id: '/super/roles'
      path: '/roles'
      fullPath: '/super/roles'
      preLoaderRoute: typeof SuperRolesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/reports': {
      id: '/super/reports'
      path: '/reports'
      fullPath: '/super/reports'
      preLoaderRoute: typeof SuperReportsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/overview': {
      id: '/super/overview'
      path: '/overview'
      fullPath: '/super/overview'
      preLoaderRoute: typeof SuperOverviewRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/maintenance': {
      id: '/super/maintenance'
      path: '/maintenance'
      fullPath: '/super/maintenance'
      preLoaderRoute: typeof SuperMaintenanceRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/logs': {
      id: '/super/logs'
      path: '/logs'
      fullPath: '/super/logs'
      preLoaderRoute: typeof SuperLogsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/database': {
      id: '/super/database'
      path: '/database'
      fullPath: '/super/database'
      preLoaderRoute: typeof SuperDatabaseRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/content': {
      id: '/super/content'
      path: '/content'
      fullPath: '/super/content'
      preLoaderRoute: typeof SuperContentRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/backup': {
      id: '/super/backup'
      path: '/backup'
      fullPath: '/super/backup'
      preLoaderRoute: typeof SuperBackupRouteImport
      parentRoute: typeof SuperRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/multimedia': {
      id: '/admin/multimedia'
      path: '/multimedia'
      fullPath: '/admin/multimedia'
      preLoaderRoute: typeof AdminMultimediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learning-materials': {
      id: '/admin/learning-materials'
      path: '/learning-materials'
      fullPath: '/admin/learning-materials'
      preLoaderRoute: typeof AdminLearningMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cultural-repository': {
      id: '/admin/cultural-repository'
      path: '/cultural-repository'
      fullPath: '/admin/cultural-repository'
      preLoaderRoute: typeof AdminCulturalRepositoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contributions': {
      id: '/admin/contributions'
      path: '/contributions'
      fullPath: '/admin/contributions'
      preLoaderRoute: typeof AdminContributionsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContributionsRoute: typeof AdminContributionsRoute
  AdminCulturalRepositoryRoute: typeof AdminCulturalRepositoryRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminLearningMaterialsRoute: typeof AdminLearningMaterialsRoute
  AdminMultimediaRoute: typeof AdminMultimediaRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContributionsRoute: AdminContributionsRoute,
  AdminCulturalRepositoryRoute: AdminCulturalRepositoryRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminLearningMaterialsRoute: AdminLearningMaterialsRoute,
  AdminMultimediaRoute: AdminMultimediaRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperRouteChildren {
  SuperBackupRoute: typeof SuperBackupRoute
  SuperContentRoute: typeof SuperContentRoute
  SuperDatabaseRoute: typeof SuperDatabaseRoute
  SuperLogsRoute: typeof SuperLogsRoute
  SuperMaintenanceRoute: typeof SuperMaintenanceRoute
  SuperOverviewRoute: typeof SuperOverviewRoute
  SuperReportsRoute: typeof SuperReportsRoute
  SuperRolesRoute: typeof SuperRolesRoute
  SuperSecurityRoute: typeof SuperSecurityRoute
  SuperSettingsRoute: typeof SuperSettingsRoute
  SuperSiteRoute: typeof SuperSiteRoute
  SuperSubscriptionRoute: typeof SuperSubscriptionRoute
  SuperUsersRoute: typeof SuperUsersRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperBackupRoute: SuperBackupRoute,
  SuperContentRoute: SuperContentRoute,
  SuperDatabaseRoute: SuperDatabaseRoute,
  SuperLogsRoute: SuperLogsRoute,
  SuperMaintenanceRoute: SuperMaintenanceRoute,
  SuperOverviewRoute: SuperOverviewRoute,
  SuperReportsRoute: SuperReportsRoute,
  SuperRolesRoute: SuperRolesRoute,
  SuperSecurityRoute: SuperSecurityRoute,
  SuperSettingsRoute: SuperSettingsRoute,
  SuperSiteRoute: SuperSiteRoute,
  SuperSubscriptionRoute: SuperSubscriptionRoute,
  SuperUsersRoute: SuperUsersRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

interface UserRouteChildren {
  UserAiChatbotRoute: typeof UserAiChatbotRoute
  UserCommunityContributionsRoute: typeof UserCommunityContributionsRoute
  UserCulturalRepositoryRoute: typeof UserCulturalRepositoryRoute
  UserEventsRoute: typeof UserEventsRoute
  UserFeedbackRoute: typeof UserFeedbackRoute
  UserLearningModulesRoute: typeof UserLearningModulesRoute
  UserMultimediaGalleryRoute: typeof UserMultimediaGalleryRoute
  UserProgressRoute: typeof UserProgressRoute
  UserSettingsRoute: typeof UserSettingsRoute
  UserStorytellingArchiveRoute: typeof UserStorytellingArchiveRoute
  UserVocabularyDictionaryRoute: typeof UserVocabularyDictionaryRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAiChatbotRoute: UserAiChatbotRoute,
  UserCommunityContributionsRoute: UserCommunityContributionsRoute,
  UserCulturalRepositoryRoute: UserCulturalRepositoryRoute,
  UserEventsRoute: UserEventsRoute,
  UserFeedbackRoute: UserFeedbackRoute,
  UserLearningModulesRoute: UserLearningModulesRoute,
  UserMultimediaGalleryRoute: UserMultimediaGalleryRoute,
  UserProgressRoute: UserProgressRoute,
  UserSettingsRoute: UserSettingsRoute,
  UserStorytellingArchiveRoute: UserStorytellingArchiveRoute,
  UserVocabularyDictionaryRoute: UserVocabularyDictionaryRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  SuperRoute: SuperRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
